import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../components/style/globals.css";
import { Navbar } from "../components/molecules/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-[var(--color-neutral-lighter)]`}
      >
        <div className="w-full px-3 py-4">
          <Navbar 
          content={[
            { label: "Home", href: "/" },
            { label: "About", href: "/about" },
            { label: "Contact", href: "/contact" },
          ]} />
        </div>
        {children}
      </body>
    </html>
  );
}
